logging:
  level:
    org.hibernate.SQL: DEBUG
    org.apache.http.wire: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: polling

    
